// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifczv1u40kUWR8QYzc4rvixfB5t_pxK8',
    appId: '1:353909507433:web:12a3241a6f0a7a3276e9f8',
    messagingSenderId: '353909507433',
    projectId: 'greengo-c588c',
    authDomain: 'greengo-c588c.firebaseapp.com',
    storageBucket: 'greengo-c588c.firebasestorage.app',
    measurementId: 'G-M2XD4WQEMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9gBSJm8LZQId1xh_eURVJ5aSPq5HrPU',
    appId: '1:353909507433:android:0b0e2ac68463257476e9f8',
    messagingSenderId: '353909507433',
    projectId: 'greengo-c588c',
    storageBucket: 'greengo-c588c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG8UhdM1MZNoQ7UfOAQi7dXpZjED2VM9o',
    appId: '1:353909507433:ios:c51887376aabf11a76e9f8',
    messagingSenderId: '353909507433',
    projectId: 'greengo-c588c',
    storageBucket: 'greengo-c588c.firebasestorage.app',
    iosBundleId: 'com.example.innowah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG8UhdM1MZNoQ7UfOAQi7dXpZjED2VM9o',
    appId: '1:353909507433:ios:c51887376aabf11a76e9f8',
    messagingSenderId: '353909507433',
    projectId: 'greengo-c588c',
    storageBucket: 'greengo-c588c.firebasestorage.app',
    iosBundleId: 'com.example.innowah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifczv1u40kUWR8QYzc4rvixfB5t_pxK8',
    appId: '1:353909507433:web:e455cdbd0bcd007f76e9f8',
    messagingSenderId: '353909507433',
    projectId: 'greengo-c588c',
    authDomain: 'greengo-c588c.firebaseapp.com',
    storageBucket: 'greengo-c588c.firebasestorage.app',
    measurementId: 'G-WGXHGDY8R7',
  );

}